// <auto-generated />
using System;
using FlatRate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlatRate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlatRateDbContext))]
    partial class FlatRateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlatRate.Domain.Aggregates.Bills.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ElectricityCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SanitationCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("WaterCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PropertyId");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("FlatRate.Domain.Aggregates.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DefaultElectricityRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DefaultSanitationRateTier1")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DefaultSanitationRateTier2")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DefaultSanitationRateTier3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DefaultWaterRateTier1")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DefaultWaterRateTier2")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DefaultWaterRateTier3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("FlatRate.Domain.Aggregates.Properties.PropertyAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitedEmail")
                        .HasFilter("\"InvitedEmail\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("PropertyId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("PropertyAccess", (string)null);
                });

            modelBuilder.Entity("FlatRate.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FlatRate.Domain.Aggregates.Bills.Bill", b =>
                {
                    b.OwnsOne("FlatRate.Domain.ValueObjects.MeterReading", "ElectricityReading", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Closing")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ElectricityReadingClosing");

                            b1.Property<decimal>("Opening")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ElectricityReadingOpening");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("FlatRate.Domain.ValueObjects.Tariff", "ElectricityTariff", b1 =>
                        {
                            b1.Property<Guid>("BillId");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1
                                .ToJson("ElectricityTariff")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BillId");

                            b1.OwnsMany("FlatRate.Domain.ValueObjects.TariffStep", "Steps", b2 =>
                                {
                                    b2.Property<Guid>("TariffBillId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.HasKey("TariffBillId", "__synthesizedOrdinal");

                                    b2.ToTable("Bills");

                                    b2.WithOwner()
                                        .HasForeignKey("TariffBillId");
                                });

                            b1.Navigation("Steps");
                        });

                    b.OwnsOne("FlatRate.Domain.ValueObjects.MeterReading", "SanitationReading", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Closing")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("SanitationReadingClosing");

                            b1.Property<decimal>("Opening")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("SanitationReadingOpening");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("FlatRate.Domain.ValueObjects.Tariff", "SanitationTariff", b1 =>
                        {
                            b1.Property<Guid>("BillId");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1
                                .ToJson("SanitationTariff")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BillId");

                            b1.OwnsMany("FlatRate.Domain.ValueObjects.TariffStep", "Steps", b2 =>
                                {
                                    b2.Property<Guid>("TariffBillId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.HasKey("TariffBillId", "__synthesizedOrdinal");

                                    b2.ToTable("Bills");

                                    b2.WithOwner()
                                        .HasForeignKey("TariffBillId");
                                });

                            b1.Navigation("Steps");
                        });

                    b.OwnsOne("FlatRate.Domain.ValueObjects.MeterReading", "WaterReading", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Closing")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("WaterReadingClosing");

                            b1.Property<decimal>("Opening")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("WaterReadingOpening");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("FlatRate.Domain.ValueObjects.Tariff", "WaterTariff", b1 =>
                        {
                            b1.Property<Guid>("BillId");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1
                                .ToJson("WaterTariff")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BillId");

                            b1.OwnsMany("FlatRate.Domain.ValueObjects.TariffStep", "Steps", b2 =>
                                {
                                    b2.Property<Guid>("TariffBillId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.HasKey("TariffBillId", "__synthesizedOrdinal");

                                    b2.ToTable("Bills");

                                    b2.WithOwner()
                                        .HasForeignKey("TariffBillId");
                                });

                            b1.Navigation("Steps");
                        });

                    b.Navigation("ElectricityReading")
                        .IsRequired();

                    b.Navigation("ElectricityTariff")
                        .IsRequired();

                    b.Navigation("SanitationReading")
                        .IsRequired();

                    b.Navigation("SanitationTariff")
                        .IsRequired();

                    b.Navigation("WaterReading")
                        .IsRequired();

                    b.Navigation("WaterTariff")
                        .IsRequired();
                });

            modelBuilder.Entity("FlatRate.Domain.Aggregates.Properties.PropertyAccess", b =>
                {
                    b.HasOne("FlatRate.Domain.Aggregates.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
